# Generated by Django 5.2.5 on 2025-08-30 19:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('part_id', models.CharField(db_index=True, max_length=100)),
                ('color', models.CharField(db_index=True, max_length=100)),
                ('quantity_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'color', 'part_id'],
                'indexes': [models.Index(fields=['user', 'part_id', 'color'], name='inventory_i_user_id_961068_idx')],
            },
        ),
    ]
