# Generated by Django 5.2.5 on 2025-08-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBColor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('rgb', models.CharField(blank=True, max_length=6)),
                ('is_trans', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'RB Color',
                'verbose_name_plural': 'RB Colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RBPart',
            fields=[
                ('part_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('part_cat_id', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'RB Part',
                'verbose_name_plural': 'RB Parts',
                'ordering': ['part_num'],
            },
        ),
        migrations.CreateModel(
            name='RBElement',
            fields=[
                ('element_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='inventory.rbcolor')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='inventory.rbpart')),
            ],
            options={
                'verbose_name': 'RB Element',
                'verbose_name_plural': 'RB Elements',
                'indexes': [models.Index(fields=['part', 'color'], name='inventory_r_part_id_aa3798_idx')],
            },
        ),
    ]
