# Generated by Django 5.2.6 on 2025-09-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rbcolor_rbpart_rbelement'),
        ('inventory', '0003_inventoryshare'),
    ]

    operations = [
    ]
