# Generated by Django 5.2.6 on 2025-09-06 16:52

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorycollab'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorycollab',
            new_name='inventory_i_owner_i_7040c5_idx',
            old_name='inventory_owner_collab_active_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryshare',
            new_name='inventory_i_user_id_4b6206_idx',
            old_name='inventory_user_is_active_idx',
        ),
        migrations.AlterField(
            model_name='inventorycollab',
            name='token',
            field=models.SlugField(default=inventory.models._invite_token, max_length=64, unique=True),
        ),
    ]
