# Generated by Django 5.2.6 on 2025-09-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_inventory_owner_collab_active_idx_inventory_i_owner_i_7040c5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('site_name', models.CharField(blank=True, default='BlockShelf', max_length=80)),
                ('items_per_page', models.PositiveIntegerField(default=25)),
                ('allow_registration', models.BooleanField(default=True)),
                ('rebrickable_api_key', models.CharField(blank=True, max_length=80)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'App configuration',
                'verbose_name_plural': 'App configuration',
            },
        ),
    ]
