# Generated by Django on production - index name normalization
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_note'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='inventory_n_user_id_f5c060_idx',
            old_name='inventory_n_user_id_7a8b9c_idx',
        ),
    ]
